language: generic
sudo: required

services:
  - docker

install:
  - docker build .ci_support -t archlinux-julia

script:
  - docker run -v `pwd`:/io archlinux-julia /io/.ci_support/run_docker_build.sh
