language: generic
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=openturns/archlinux-python

install:
  - docker pull ${DOCKER_IMAGE}

script:
  - docker run -v `pwd`:/io ${DOCKER_IMAGE} /io/run_docker_build.sh

